# API Keys
polygon_api_key: "YOUR_POLYGON_API_KEY_HERE"

# Live Data Configuration
live_data_provider: "yfinance"  # Options: "yfinance", "polygon"

# Base Directory Configuration
data_directory: "data"
artifacts_directory: "artifacts"