site_name: QuantFin
site_author: Diljit Singh
site_description: "A Python library for quantitative finance."
site_url: https://github.com/diljit22/

repo_url: https://github.com/diljit22/quantfin
repo_name: quantfin

docs_dir: docs


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_signature_annotations: true
  - section-index


markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"


nav:
  - Home: index.md
  - User Guide:
      - Introduction: guide/introduction.md
      - Installation: guide/installation.md
      - Getting Started: guide/getting_started.md
  - API Reference:
      - Atoms:
          - Bond: reference/atoms/bond.md
          - Option: reference/atoms/option.md
          - Rate: reference/atoms/rate.md
          - Stock: reference/atoms/stock.md
      - Calibration:
          - Calibrator: reference/calibration/calibrator.md
          - IV Surface: reference/calibration/iv_surface.md
      - Data:
          - Historical Manager: reference/data/historical_manager.md
          - Market Data Manager: reference/data/market_data_manager.md
      - Models:
          - Base Model: reference/models/base/base_model.md
          - Black-Scholes-Merton: reference/models/bsm.md
          - Heston: reference/models/heston.md
          - Merton Jump Diffusion: reference/models/merton_jump.md
          - And...: reference/models/index.md
      - Parity:
          - Implied Rate: reference/parity/implied_rate.md
          - Parity Model: reference/parity/parity_model.md
      - Techniques:
          - Base Technique: reference/techniques/base/base_technique.md
          - Monte Carlo: reference/techniques/monte_carlo.md
          - Finite Difference: reference/techniques/pde.md
          - FFT: reference/techniques/fft.md
  - Benchmark:
      - Introduction: benchmark/index.md
      - Running Benchmarks: benchmark/running.md
